name: Deploy from Obsidian notes

on:
  push:
    branches:
      - master

jobs:
  publish_job:
    runs-on: ubuntu-latest
    name: Publish Obsidian notes to Github pages
    steps:
      - uses: haxrob/obsidian-to-hugo-pages@v0.1.3
        with:
          vault-path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
